name: Super-Linter

on: push

jobs:
    super-lint:
      name: Lint our code
      runs-on: ubuntu-latest

      steps:
        - name: Get copy of repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
      
        - name: Run Super-Linter
          uses: github/super-linter@v4
          env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: "master"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    docker:
      runs-on: ubuntu-latest
      needs: super-lint
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: markom565/kii-demo:latest